<?php

namespace Tests\Unit;

use App\Entities\TaskListEntity;
use App\Repositories\TaskListsRepository;
use App\Services\TaskListsService;
use Carbon\Carbon;
use Mockery\MockInterface;
use Tests\TestCase;

class TaskListServiceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Carbon::setTestNow(Carbon::now());
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_it_is_able_to_create_task_lists()
    {
        $id     = fake()->uuid;
        $name   = fake()->sentence;
        $userId = fake()->numberBetween(1, PHP_INT_MAX);

        $this->mock(TaskListsRepository::class, static function (MockInterface $mock) use ($id, $name, $userId) {
            $mock->shouldReceive('createTaskList')->withArgs(fn($id, $name, $userId) => true)->once()->andReturn(
                new TaskListEntity($id, $name, $userId, [], Carbon::now())
            );
        });
        $service = resolve(TaskListsService::class);

        $service->createTaskList('My first task list', $userId, $id);
    }
}
