<?php

namespace Tests\Unit;

use App\Repositories\TaskListsRepository;
use App\Services\TaskListsService;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\WithFaker;
use Mockery\MockInterface;
use PHPUnit\Framework\TestCase;

class TaskListServiceTest extends TestCase
{
    use WithFaker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Carbon::setTestNow(Carbon::now());
        $this->setUpFaker();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_it_is_able_to_create_task_lists()
    {
        $id = $this->faker->uuid;
        $name = $this->faker->sentence;
        $userId = $this->faker->numberBetween(1, PHP_INT_MAX);

        $this->mock(TaskListsRepository::class, static function (MockInterface $mock) use ($id, $name, $userId) {
            $mock->shouldReceive('createTaskList')->withArgs([$id, $name, $userId])->once();
        });
        $service = resolve(TaskListsService::class);

        $service->createTaskList('My first task list');
    }
}
